#! /usr/bin/bash

# Correct starting directory in Windows Terminal settings
#	- add "startingDirectory": "//wsl$/Ubuntu/home/james/"

set_correct_working_dir() {
	echo -n "Setting working directory to script location.. "
	SOURCE="${BASH_SOURCE[0]}"
	while [[ -h "$SOURCE" ]]; do
		DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
		SOURCE="$(readlink "$SOURCE")"
		[[ ${SOURCE} != /* ]] && SOURCE="$DIR/$SOURCE"
	done
	DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
	echo "Done: ${DIR}"
}

set_correct_working_dir

# # Remove need for sudo password
sudo echo "${USER} ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/${USER} > /dev/null

# # Modernise distribution
sudo apt update -y && sudo apt upgrade -y && sudo apt dist-upgrade -y && sudo apt autoremove && sudo apt install git-all curl wget -y

# # ZSH and Oh-My-Zsh
sudo apt install zsh -y
sudo sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# # Config
cp ${DIR}/.zshrc ${HOME}
cp ${DIR}/.p10k.zsh ${HOME}
# # sed -i 's/ZSH_THEME="robbyrussell"/ZSH_THEME="powerlevel10k\/powerlevel10k"/g' ~/.zshrc

# # VS Code Server
code

# # git credentials
git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/libexec/git-core/git-credential-manager.exe"

# # dev tools
# # pyenv go poetry
